# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47e8ab28931917b1ae4d849827906dba34253c5b2d0bbf2cd78f9a276e3a87cc602abf285e16768d5cc8e43aa556d83fa21ec561833b2e728b36910458bb1e27

test:
  secret_key_base: 0c0ad1453601a5e15a16c01045aa2c9e6fb55fd987f9ff95df3c2f7fd05301b5319630400d24f4d833983e80ef20cc2081d853690a793d04c046c2f95d833dd5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
